<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SectionTypes\Blue.png" />
    <None Remove="SectionTypes\Finish.png" />
    <None Remove="SectionTypes\LeftCorner.jpg" />
    <None Remove="SectionTypes\Lime.png" />
    <None Remove="SectionTypes\Orange.png" />
    <None Remove="SectionTypes\Pink.png" />
    <None Remove="SectionTypes\RightCorner.png" />
    <None Remove="SectionTypes\StartGrid.png" />
    <None Remove="SectionTypes\Straight_Horizontal.png" />
    <None Remove="SectionTypes\Straight_Vertical.jpg" />
    <None Remove="SectionTypes\SuperLeftCorner.jpg" />
    <None Remove="SectionTypes\SuperRightCOrner.jpg" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="{d37e2a3e-8545-3a39-9f4f-31827c9124ab}">
      <Guid>d37e2a3e-8545-3a39-9f4f-31827c9124ab</Guid>
      <VersionMajor>2</VersionMajor>
      <VersionMinor>4</VersionMinor>
      <WrapperTool>tlbimp</WrapperTool>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="SectionTypes\Blue.png" />
    <Content Include="SectionTypes\Finish.png" />
    <Content Include="SectionTypes\LeftCorner.jpg" />
    <Content Include="SectionTypes\Lime.png" />
    <Content Include="SectionTypes\Orange.png" />
    <Content Include="SectionTypes\Pink.png" />
    <Content Include="SectionTypes\RightCorner.png" />
    <Content Include="SectionTypes\StartGrid.png" />
    <Content Include="SectionTypes\Straight_Horizontal.png" />
    <Content Include="SectionTypes\Straight_Vertical.jpg" />
    <Content Include="SectionTypes\SuperLeftCorner.jpg" />
    <Content Include="SectionTypes\SuperRightCOrner.jpg" />
  </ItemGroup>

</Project>