<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TrackVisual\Blue.png" />
    <None Remove="TrackVisual\Finish.png" />
    <None Remove="TrackVisual\LeftCorner.jpg" />
    <None Remove="TrackVisual\Lime.png" />
    <None Remove="TrackVisual\Orange.png" />
    <None Remove="TrackVisual\Pink.png" />
    <None Remove="TrackVisual\RightCorner.png" />
    <None Remove="TrackVisual\StartGrid.png" />
    <None Remove="TrackVisual\Straight_Horizontal.png" />
    <None Remove="TrackVisual\Straight_Vertical.jpg" />
    <None Remove="TrackVisual\SuperLeftCorner.jpg" />
    <None Remove="TrackVisual\SuperRightCOrner.jpg" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="{d37e2a3e-8545-3a39-9f4f-31827c9124ab}">
      <Guid>d37e2a3e-8545-3a39-9f4f-31827c9124ab</Guid>
      <VersionMajor>2</VersionMajor>
      <VersionMinor>4</VersionMinor>
      <WrapperTool>tlbimp</WrapperTool>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="TrackVisual\Blue.png" />
    <Content Include="TrackVisual\Finish.png" />
    <Content Include="TrackVisual\LeftCorner.jpg" />
    <Content Include="TrackVisual\Lime.png" />
    <Content Include="TrackVisual\Orange.png" />
    <Content Include="TrackVisual\Pink.png" />
    <Content Include="TrackVisual\RightCorner.png" />
    <Content Include="TrackVisual\StartGrid.png" />
    <Content Include="TrackVisual\Straight_Horizontal.png" />
    <Content Include="TrackVisual\Straight_Vertical.jpg" />
    <Content Include="TrackVisual\SuperLeftCorner.jpg" />
    <Content Include="TrackVisual\SuperRightCOrner.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Controller\Controller.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>

</Project>